### ISSUE TITLE
缺少score_qa函数定义

### ISSUE THREAD

**Issue by permanzh** [Steven-Luo/MasteringRAG#1]
运行出错, 缺少score_qa函数定义
![image](https://github.com/user-attachments/assets/fc358c94-7e58-47e4-a8dd-9fac8823e818)

**Comment by Steven-Luo** [comment]
已更新，也可以参考“00_PDF解析与QA抽取_v1.1.ipynb”文件，打分的prompt做了修改，并且全部重新跑了一遍
