### ISSUE TITLE
函数split_docs未导入pickle报错

### ISSUE THREAD

**Issue by dej4vu** [Steven-Luo/MasteringRAG#2]
报错信息如下：

NameError Traceback (most recent call last)
Cell In[24], line 1
----> 1 splitted_docs = split_docs(documents, os.path.join(output_dir, 'split_docs.pkl'), chunk_size=500, chunk_overlap=50)
2 splitted_docs_large = split_docs(merged_docs, os.path.join(output_dir, 'split_docs_large.pkl'), chunk_size=1500, chunk_overlap=100)

Cell In[23], line 9
7 if os.path.exists(filepath) and not force_split:
8 print('found cache, restoring...')
----> 9 return pickle.load(open(filepath, 'rb'))
11 splitter = RecursiveCharacterTextSplitter(
12 chunk_size=chunk_size,
13 chunk_overlap=chunk_overlap,
14 separators=seperators
15 )
16 split_docs = splitter.split_documents(documents)

NameError: name 'pickle' is not defined

**Comment by Steven-Luo** [comment]
已更新
